spring:
  application:
    name: planedle

  datasource:
    spring:
      datasource:
        url: jdbc:postgresql://postgres.railway.internal:5432/railway?sslmode=require
        username: postgres
        password: MsggnRTrrDFGnoOfTxXMDIhfQWRLEHbo
        #jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:planedle}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
